version: '3'
services:
  api:
    build: "."
    container_name: api
    restart: always
    environment:
      - DB_PRODUCTION_URL=mongodb://root:root@mongodb:27017/url_monitor
      - PORT=4000
      - NODE_ENV=production
      - JWT_KEY=
      - JWT_VERIFICATION_KEY=
      - REDIS_URL=redis://cache:6379
      - EMAIL_HOST=smtp.gmail.com
      - EMAIL_PORT=465
      - EMAIL_USERNAME=
      - EMAIL_PASSWORD=
      - EMAIL_VERIFICATION_URL=/api/v1/users/verify/
      - QUEUE_NAME=job-scheduler
      - SERVER_HOST=http://0.0.0.0:4000
    ports:
      - 4000:4000
    depends_on:
      - mongodb
      - cache
  cache:
    container_name: cache
    restart: always
    image: redis:latest
    ports: 
      - 6390:6379
    volumes:
      - cache:/data
  mongodb:
    container_name: mongodb
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27019:27017
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:
  cache:
