version: '3'
services:
  api:
    build: "."
    container_name: api
    restart: always
    environment:
      - DB_PRODUCTION_URL=mongodb://root:root@mongodb:27017/url_monitor_development
      - PORT=4000
      - NODE_ENV=production
      - JWT_KEY=jadshdjhdsajahdsjsadhq8981208dscasdasd
      - JWT_VERIFICATION_KEY=fsdjhsfdkjhfsdjkfdshjsfdk
      - REDIS_HOST=cache
      - REDIS_PORT=6379
      - EMAIL_HOST=smtp.gmail.com
      - EMAIL_PORT=465
      - EMAIL_USERNAME=urlmonitor.22@gmail.com
      - EMAIL_PASSWORD=ANONY@@mous
      - EMAIL_VERIFICATION_URL=http://api:4000/api/v1/users/verify/
      - QUEUE_NAME=job-scheduler
    depends_on:
      - mongodb
      - cache
  cache:
    image: redis:6.2-alpine
    container_name: cache
    restart: always
    ports:
      - '6379:6379'
    command: redis-server
    volumes:
      - cache:/data
  mongodb:
    container_name: mongodb
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27019:27019
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:
  cache:
